### ISSUE TITLE
Update+set = Invalid or unexpected token

### ISSUE THREAD

**Issue by tityrus** [dan-eyles/sculejs#63] opened 2017-07-13 14:48 UTC
Upon doing update() with $set() an exception is thrown when there are special characters like € in one of the fields:

```
[ERROR] TiExceptionHandler: (main) [47603,53314] ----- Titanium Javascript Runtime Error -----
[ERROR] TiExceptionHandler: (main) [0,53314] - In undefined:18,83
[ERROR] TiExceptionHandler: (main) [4,53318] - Message: Uncaught SyntaxError: Invalid or unexpected token
[ERROR] TiExceptionHandler: (main) [1,53319] - Source: 		engine.$set(engine.traverseObject("admission", o), "€ 8, € 6\n \n
```

**Comment by cammydan** [comment] 2017-07-13 16:23
Hey Joris, thanks for the detailed debugging work on this ticket. 

I won't have time to look into this until late next week - if you'd like to take a shot at fixing the issue yourself in the mean time and submitting a PR I'd be happy to review the changes.

Thanks again for taking the time to raise this issue.

Regards.
Dan

**Comment by cammydan** [comment] 2017-07-13 16:29
Just before I head off to bed I had a quick look at the code and I've figured out where the issue is:

https://github.com/deyles/sculejs/blob/master/lib/com.scule.js#L4483

It looks like the error is raised when scule attempts to eval code into the current execution context with weird characters in the property names being referenced by the query engine. This could be fixed by changing the following line:

```javascript
clauses.push('\t\tengine.' + key + '(engine.traverseObject(' + JSON.stringify(operand) + ', o), ' + JSON.stringify(subQuery[operand]) + ', ' + JSON.stringify(upsert) + ');');
```
To something like:

```javascript
clauses.push('\t\tengine["' + key + '"](engine.traverseObject(' + JSON.stringify(operand) + ', o), ' + JSON.stringify(subQuery[operand]) + ', ' + JSON.stringify(upsert) + ');');
```
There are probably other affected sections of code with the same (or similar) issues.

**Comment by deyles-zz** [comment] 2017-07-13 16:31
Hey Joris, thanks for the detailed debugging work on this ticket.

I won't have time to look into this until late next week - if you'd like to take a shot at fixing the issue yourself in the mean time and submitting a PR I'd be happy to review the changes.

Thanks again for taking the time to raise this issue.

Regards.
Dan

**Comment by deyles-zz** [comment] 2017-07-13 16:31
Just before I head off to bed I had a quick look at the code and I've figured out where the issue is:

https://github.com/deyles/sculejs/blob/master/lib/com.scule.js#L4483

It looks like the error is raised when scule attempts to eval code into the current execution context with weird characters in the property names being referenced by the query engine. This could be fixed by changing the following line:

```javascript
clauses.push('\t\tengine.' + key + '(engine.traverseObject(' + JSON.stringify(operand) + ', o), ' + JSON.stringify(subQuery[operand]) + ', ' + JSON.stringify(upsert) + ');');
```
To something like:

```javascript
clauses.push('\t\tengine["' + key + '"](engine.traverseObject(' + JSON.stringify(operand) + ', o), ' + JSON.stringify(subQuery[operand]) + ', ' + JSON.stringify(upsert) + ');');
```
There are probably other affected sections of code with the same (or similar) issues.

**Comment by tityrus** [comment] 2017-07-19 12:18
Hi Dan!

Thanks for your reply.

Unfortunately it's not the attribute name that has the symbols, but its value. I tried your suggested solution, and indeed, it gives the same error because the € sign was not in the attribute name but in the value.

I have done some further debugging. Symbols in the value that cause the exception include:
%
€
\u2028

So it seems like the affected part is:
`JSON.stringify(subQuery[operand])`

**Comment by tityrus** [comment] 2017-07-24 11:50
Update.

In the end the error was due to the presence of the following unicode characters in the value:

\u2028
\u200B

Those don't get digested well by the JavaScript functions used by SculeJS. If you run across this issue, I would recommend doing a string replace for those and replacing them with the empty string "".

In case you are interested where those come from, they appeared in the database by users copy-pasting data from Word into CKEditor (in a web app). Go figure. Since they are invisible characters, they were hard to track down in the logs, sorry for the confusion in the previous messages.

**Closed as completed** 2017-08-02 12:50 UTC
